<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Done_Button</name>
   <tag></tag>
   <elementGuidId>2ddf1f06-09e5-49fa-bd7b-79fd1089e411</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.my-auto.mx-auto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Layout']/div/div/div/div[2]/div[2]/div[2]/div/div[2]/div[2]/a/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e9c5bc2f-d78b-4d8b-9d8c-6b90c1af96f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-auto mx-auto</value>
      <webElementGuid>602ff5ba-2e48-4b35-bdca-7214ce7e5b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>e784c1bf-8f2e-4bd2-979e-ae0d91e10152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Layout&quot;)/div[@class=&quot;layout-render-section row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;d-flex&quot;]/div[2]/div[@class=&quot;new-design-form-style&quot;]/div[@class=&quot;d-flex flex-column text-center bg-white&quot;]/div[@class=&quot;mt-4 mx-auto px-0 col-3&quot;]/a[1]/button[@class=&quot;neo-btn-new-design&quot;]/p[@class=&quot;my-auto mx-auto&quot;]</value>
      <webElementGuid>3f54c529-2a7f-47f2-afbf-54f3bed3c118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Layout']/div/div/div/div[2]/div[2]/div[2]/div/div[2]/div[2]/a/button/p</value>
      <webElementGuid>90934b6f-8379-4c76-b4e9-60861319e381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='//url(#linearGradient-1)//url(#linearGradient-2)'])[1]/following::p[2]</value>
      <webElementGuid>8ab75017-da18-4302-9f5e-eb8d73cc47f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modify Internal Beneficiary'])[1]/following::p[2]</value>
      <webElementGuid>479c57ea-ffab-4fb9-b1ac-0122c9385bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>2373d39c-b828-4bb2-9ac5-4c7ae9d6cb69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/p</value>
      <webElementGuid>c739f6fb-cdd1-49d8-a29c-f8c444218529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>033afa35-8335-4bcc-8633-4dd73b2da131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
